# Generated by Django 5.1.4 on 2025-01-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=33, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_en',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_ru',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_en',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='address_ru',
            field=models.CharField(max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
