# Generated by Django 5.1.4 on 2025-01-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0005_alter_store_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='price',
            new_name='combo_price',
        ),
    ]
